#include <catch.hpp>
#include <common/math_const.h>

TEST_CASE("math_const")
{
    REQUIRE(IEP_E == M_E);
    REQUIRE(IEP_LOG2E == M_LOG2E);
    REQUIRE(IEP_LOG10E == M_LOG10E);
    REQUIRE(IEP_SQRT2 == M_SQRT2);
    REQUIRE(IEP_SQRT1_2 == M_SQRT1_2);
    REQUIRE(IEP_SQRT3 == M_SQRT3);
    REQUIRE(IEP_PI == M_PI);
    REQUIRE(IEP_PI_2 == M_PI_2);
    REQUIRE(IEP_PI_4 == M_PI_4);
    REQUIRE(IEP_SQRTPI == M_SQRTPI);
    REQUIRE(IEP_2_SQRTPI == M_2_SQRTPI);
    REQUIRE(IEP_1_PI == M_1_PI);
    REQUIRE(IEP_2_PI == M_2_PI);
    REQUIRE(IEP_LN10 == M_LN10);
    REQUIRE(IEP_LN2 == M_LN2);
    REQUIRE(IEP_LNPI == M_LNPI);
    REQUIRE(IEP_EULER == M_EULER);
}
